/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import models.NumerosNaturaisTable;

import java.math.BigInteger;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lusra
 */
public class MainUI extends javax.swing.JFrame {
    
    private void SetImageLabel (JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        getContentPane().setBackground(Color.red);
        
        Table1.setEnabled(false);
        
        SetImageLabel(Label3_flamengo, "src/images/download.jpg");
        SetImageLabel(Label3_eu, "src/images/image.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextField1_firstNumber = new javax.swing.JTextField();
        TextField2_secondNumber = new javax.swing.JTextField();
        Button1_calcular = new javax.swing.JButton();
        Label3_flamengo = new javax.swing.JLabel();
        Label3_eu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table1);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Primeiro Número: ");

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Segundo  Número:");

        TextField2_secondNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField2_secondNumberActionPerformed(evt);
            }
        });

        Button1_calcular.setBackground(new java.awt.Color(204, 0, 40));
        Button1_calcular.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Button1_calcular.setText("CALCULAR");
        Button1_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1_calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(Label3_flamengo, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextField1_firstNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(TextField2_secondNumber))
                .addGap(18, 18, 18)
                .addComponent(Button1_calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label3_eu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Label3_flamengo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label3_eu, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(TextField1_firstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextField2_secondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Button1_calcular)
                            .addGap(27, 27, 27))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField2_secondNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField2_secondNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField2_secondNumberActionPerformed

    private void Button1_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1_calcularActionPerformed
        // TODO add your handling code here:
        try{
            String textNumber1 = TextField1_firstNumber.getText();
            String textNumber2 = TextField2_secondNumber.getText();
            
            BigInteger number1 = new BigInteger(textNumber1);
            NumerosNaturaisTable n1 = new NumerosNaturaisTable(number1);

            BigInteger number2 = new BigInteger(textNumber2);
            NumerosNaturaisTable n2 = new NumerosNaturaisTable(number2);
            
            Table1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {"ITEM", "Numero1", "Numero2"}
            ));
            
            DefaultTableModel model =  (DefaultTableModel)Table1.getModel();
            
            model.addRow(new Object[]{"FATORIAL", n1.mathFatorial().get(), n2.mathFatorial().get()});
            model.addRow(new Object[]{"NÚMERO PERFEITO", n1.mathNumeroPerfeito() ? "SIM" : "NÃO", n2.mathNumeroPerfeito() ? "SIM" : "NÃO"});
            model.addRow(new Object[]{"CAPICUA", n1.mathCapicua() ? "SIM" : "NÃO", n2.mathCapicua() ? "SIM" : "NÃO"});
            model.addRow(new Object[]{"QUADRADO PERFEITO", n1.mathQuadradoPerfeito() ? "SIM" : "NÃO", n2.mathQuadradoPerfeito() ? "SIM" : "NÃO"});
            model.addRow(new Object[]{"NÚMERO PRIMO", n1.mathPrimo() ? "SIM" : "NÃO", n2.mathPrimo() ? "SIM" : "NÃO"});
            model.addRow(new Object[]{"BASE 10 PARA BASE 2", n1.mathConverteParaBaseX(2), n2.mathConverteParaBaseX(2)});
            model.addRow(new Object[]{"BASE 10 PARA BASE 8", n1.mathConverteParaBaseX(8), n2.mathConverteParaBaseX(8)});
            model.addRow(new Object[]{"BASE 10 PARA BASE 16", n1.mathConverteParaBaseX(16), n2.mathConverteParaBaseX(16)});
            model.addRow(new Object[]{"MÁXIMO DIVISOR COMUM", n1.mathMDC(n2).get(), n2.mathMDC(n1).get()});
            model.addRow(new Object[]{"MÍNIMO MÚLTIPLO COMUM", n1.mathMMC(n2).get(), n2.mathMMC(n1).get()});
            model.addRow(new Object[]{"PRIMOS ENTRE SI", n1.mathPrimosEntreSi(n2) ? "SIM" : "NÃO", n2.mathPrimosEntreSi(n1) ? "SIM" : "NÃO"});
        } catch (Exception erro){
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_Button1_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1_calcular;
    private javax.swing.JLabel Label3_eu;
    private javax.swing.JLabel Label3_flamengo;
    private javax.swing.JTable Table1;
    private javax.swing.JTextField TextField1_firstNumber;
    private javax.swing.JTextField TextField2_secondNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
